name: user_app
description: "IoT Care App - Flutter Dashboard 중심 User-App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리
  provider: ^6.1.1

  # HTTP 클라이언트
  dio: ^5.4.0

  # WebSocket
  web_socket_channel: ^2.4.0

  # 로컬 저장소
  shared_preferences: ^2.5.3
  hive: ^2.2.3

  # 차트 및 데이터 시각화
  fl_chart: ^0.66.0

  # 날짜/시간 처리
  intl: ^0.19.0

  # 이미지 처리
  cached_network_image: ^3.3.0

  # 유틸리티
  uuid: ^4.2.1
  json_annotation: ^4.8.1

  # UI 컴포넌트
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 코드 생성
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  # 테스트 도구
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1

  # 코드 품질
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
