version: '3.8'

services:
  # FastAPI 애플리케이션
  app:
    build: .
    container_name: iot-care-app-dev
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
      - ./logs:/app/logs
      - ./config:/app/config
    env_file:
      - .env.dev
    depends_on:
      - redis
    networks:
      - iot-care-dev-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  # Redis (캐시, 세션, 태스크 큐)
  redis:
    image: redis:7-alpine
    container_name: iot-care-redis-dev
    restart: unless-stopped
    ports:
      - "16380:6379"
    volumes:
      - redis_dev_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - iot-care-dev-network

  # Caddy 웹서버 (개발용 - SSL 없음)
  caddy:
    image: caddy:2-alpine
    container_name: iot-care-caddy-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_dev_data:/data
      - caddy_dev_config:/config
    depends_on:
      - app
    networks:
      - iot-care-dev-network

volumes:
  redis_dev_data:
    driver: local
  caddy_dev_data:
    driver: local
  caddy_dev_config:
    driver: local

networks:
  iot-care-dev-network:
    driver: bridge
